name: Build and test Android (debug)

on:
  pull_request:
    branches:
      - main
      - 'releases/**'
      - develop
      - bugfix

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Build Project
        run: ./gradlew bundleDebug

  unit-test-shared:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Run Shared Unit Tests
        run: ./gradlew :shared:testDebugUnitTest

  unit-test-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Run Android Unit Tests
        run: ./gradlew :androidApp:testDebugUnitTest