name: Android build

on:
  push:
    branches:
      - develop

jobs:
  android_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Build Project
        run: ./gradlew assemble

      - name: Publish to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: Internal
          file: androidApp/build/outputs/apk/debug/androidApp-debug.apk
          debug: true