name: Build and test debug version

on:
  pull_request:
    branches:
      - main
      - 'releases/**'
      - develop
      - bugfix

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: ./gradlew assembleDebug

  unit-test-shared-android:
    name: Unit Test Shared Android
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Shared Unit Tests
        run: ./gradlew :shared:testDebugUnitTest

  unit-test-android:
    name: Unit Test Android
    needs: [ unit-test-shared-android, unit-test-shared-ios ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Android Unit Tests
        run: ./gradlew :androidApp:TestDebugUnitTest

  unit-test-shared-ios:
    name: Unit Test Shared iOS
    needs: build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup xcode-select
        uses: devbotsxyz/xcode-select@v1

      - name: Install cocoapods-generate
        run: gem install cocoapods-generate

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run Shared Unit Tests
        run: ./gradlew :shared:IosX64Test

  unit-test-ios:
    name: Unit Test iOS
    needs: [ unit-test-shared-android, unit-test-shared-ios ]
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup xcode-select
        uses: devbotsxyz/xcode-select@v1

      - name: Install cocoapods-generate
        run: gem install cocoapods-generate

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Fix shared module issue
        run: ./gradlew generateDummyFramework

      - name: Pod Install
        run: pod install --project-directory=iosApp

      - name: Run iOS Unit Tests
        run: xcodebuild clean test -workspace iosApp/iosApp.xcworkspace -scheme iosApp -destination 'platform=iOS Simulator,name=iPhone 12'
